Be able to paginate the output of the tree
jonathanj/eliottree pull request #99
Opened 2020-08-21 15:25 UTC by RoyLarson

The purpose of this pull request is to allow the logs to be viewed as chunks. This is useful for long running tasks.

```
(eliot_tree) λ eliot-tree test.log -l 0 --chunk-size 10
82df7cd8-68b4-415c-ae30-e57f545142b4
└── start_fib/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.016s
    ├── FIB/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.003s
    │   ├── n: 10
    │   ├── FIB/2/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.003s
    │   │   ├── n: 9
    │   │   ├── FIB/2/2/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.003s
    │   │   │   ├── n: 8
    │   │   │   ├── FIB/2/2/2/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.003s
    │   │   │   │   ├── n: 7
Press any key to continue or 'X' to exit or 'T' for next task:

    │   │   │   │   ├── FIB/2/2/2/2/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.001s
    │   │   │   │   │   ├── n: 6
    │   │   │   │   │   ├── FIB/2/2/2/2/2/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.001s
    │   │   │   │   │   │   ├── n: 5
    │   │   │   │   │   │   ├── FIB/2/2/2/2/2/2/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.001s
    │   │   │   │   │   │   │   ├── n: 4
    │   │   │   │   │   │   │   ├── FIB/2/2/2/2/2/2/2/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.000s
    │   │   │   │   │   │   │   │   ├── n: 3
    │   │   │   │   │   │   │   │   ├── FIB/2/2/2/2/2/2/2/2/2/1 ⇒ started 2020-08-21 15:16:13Z ⧖ 0.000s
    │   │   │   │   │   │   │   │   │   ├── n: 2
Press any key to continue or 'X' to exit or 'T' for next task:
```

to make the log for the example I ran the code below several times
```
from pathlib import Path
from eliot import log_call, to_file, log_message, start_task, start_action
to_file(Path("test.log").open("ab+"))

@log_call(action_type="FIB", include_args=['n'], include_result=True)
def fib(n):
    if n==1 or n==0:
        return n
    return n+fib(n-1)

def main(n):
    with start_task(action_type="start_fib") as task:
        n = fib(n)
        task.log(message_type='result', n=n)
    print(n)

if __name__=='__main__':
    main(30)

```

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonathanj/eliottree/99)

2020-08-26 14:10 UTC, jonathanj requested changes
Thanks for the contribution! I've added some comments to the diff where I think some more iteration is required.

As far as the "chunked" name goes, I'm not a fan. I think a better name is "pagination", with the option being called `--page-size`.

2020-08-26 14:10 UTC, jonathanj commented on src/eliottree/tree_format/_text.py
> +            )
You can avoid duplicating the `write_lines = …` code by slightly restructuring your loop:

```python
while True:
  write_lines = …
  if not write_lines:
    break
  yield write_lines
```

2020-08-26 14:10 UTC, jonathanj commented on src/eliottree/tree_format/_text.py
> +        write_lines = u"\n".join((line for _, line in zip(range(chunk_size), lines)))
I think what you want here is [`partition`](https://toolz.readthedocs.io/en/latest/api.html#toolz.itertoolz.partition) from the `toolz` package (which is already a dependency):

```python
from toolz import partition

write_lines = '\n'.join(partition(lines, chunk_size))
```

2020-08-26 14:10 UTC, jonathanj commented on src/eliottree/_cli.py
> +    parser.add_argument('--chunk-size',
Please add a `metavar` key, I would suggest calling it `LINES` so that it's clear what the unit of size is.

2020-08-26 14:10 UTC, jonathanj commented on .gitignore
> +.vscode/
Please remove this, I don't want every editor's cruft exhaustively listed in the project's ignore file. Rather avoid adding this file when committing.

2020-08-27 15:56 UTC, RoyLarson commented on src/eliottree/_cli.py
> +                        help='''Break the print output into chunks of size. 0 prints all lines''')
as you mentioned page-size is a much better name
Does this work for the description
```
'''Page through the log file displaying this many new lines at once. If this is 0 then all lines will be output'''
```

2020-09-19 13:34 UTC, RoyLarson reviewed
Updates that match changes requested by Jonathan

2021-01-18 22:53 UTC, RoyLarson commented
Any update on other changes you would like?

2023-09-22 12:53 UTC, closed without merging